### PR TITLE
Replace gateways across codebase and markdown copy

### PR DESCRIPTION
**Pull request by pyr0gan**
## Purpose
Now that DataHub utilizes sales form signup (instead of self-serve signup), Learn users will need to rely on public gateways to complete the pathways.

## Description
- Markdown copy updated across all pathways to remove references to DataHub
- Removes the API Key requirements for `.env.local`, with the exception of The Graph pathway which has been changed back to use Alchemy for access to Ethereum. 
- The utility functions no longer reference or use DataHub URLs from `.env.local`
- The file `utils/datahub.ts` has been renamed to `utils/external.ts` and all references have been updated
- The repository URL for `learn-tutorials` in the CustomMarkdown component was updated from the previous name of `datahub-learn`

Screen Shot 2022-08-23 at 12 07 36 PM

### CODE REVIEW

**Comment by dgamboa** [comment]
Let's explore the failing security check

**Review by dgamboa — APPROVED** [review]
This is great @pyr0gan 
Let's go ahead and merge it once we addressed the security issue, and prepare a plan to test the remaining pathways over the course of the week to make sure we've caught any major issues

**Comment by pyr0gan** [comment]
> Let's explore the failing security check

@dgamboa It's being triggered by test private key in one of the test cases for Avalanche.

Screen Shot 2022-08-23 at 12 26 22 PM

Screen Shot 2022-08-23 at 12 27 52 PM

**Comment by dgamboa** [comment]
> 

Roger that, g2g then

**Pull request merged**
