### PR TITLE
Update Solana setup for Gitpod

### PR DESCRIPTION
**Pull request by pyr0gan**
- Added instructions to clarify the Solana CLI

Screen Shot 2021-11-09 at 10 50 05 AM

This addresses an issue where users might attempt to run a Test Validator before installing the Solana CLI.

### CODE REVIEW

**Comment by guillaumegaluz** [comment]
Aren't users going to see this after they've already chosen between Gitpod and local dev?

**Comment by pyr0gan** [comment]
> Aren't users going to see this after they've already chosen between Gitpod and local dev?

The rationale for using the same heading here is to catch the attention of users who are using a local clone of the repo. In all cases, the Solana CLI needs to be installed. I believe this is clearer, and removes the blockquote as well:

Screen Shot 2021-11-10 at 1 02 53 PM

**Comment by guillaumegaluz** [comment]
ok i see, sorry! good idea

but i preferred what you did before tbh. using the alert was the right way to do it
also i would keep the "if you have cloned this locally" (better to have this be "positive" than "if you have not done X")
lastly, can we use an alert hint (yellow) instead of the blue one? i think bartosz or daniel fixed this

i'll approve now - make some changes and merge!

**Review by guillaumegaluz — APPROVED** [review]

**Comment by pyr0gan** [comment]
@guillaumegaluz 
Screen Shot 2021-11-10 at 4 36 55 PM

**Pull request merged**
