### PR TITLE
Update Near.tsx

### PR DESCRIPTION
**Pull request by decentra1ized**
Correcting the errors written as Avalanche.
(There was an execution error in Step 3 of the Near Pathway, No further progress was possible.)

### CODE REVIEW

**Comment by zurgl** [comment]
@decentra1ized Thanks!

**Comment by zurgl** [comment]
@decentra1ized Could you log an issue on the repository about the error on Step 3?
In the next 48h, we're going to re-work the NEAR pathways then It could be interesting to learn more about your issue.

**Comment by decentra1ized** [comment]
@zurgl The problem that occurred in step 3 was solved by this update. should I create additional issues?

**Comment by zurgl** [comment]
> @zurgl The problem that occurred in step 3 was solved by this update. should I create additional issues?

Ok, it's solved, then no need, thanks again for your collaborations. 
Hope you enjoy the pathways, more learning resources [here](https://learn.figment.io/)
If you want to contribute and be part of the community join us on [Discord](https://discord.gg/N6q3ySb2)

**Pull request merged**
