### PR TITLE
Update Polkadot structure of get account balance

### LINKED ISSUE #227: TS highlights error in polkadot/balance.ts solution
image

### PR DESCRIPTION
**Pull request by icepaq**
Fixes #227

Changed code based on https://github.com/jacogr/api-test-4450/blob/master/index.ts

### CODE REVIEW

**Comment by zurgl** [comment]
@icepaq Thanks.
Would be really nice if you can update the corresponding md file?
https://github.com/figment-networks/learn-web3-dapp/blob/main/markdown/polkadot/GET_BALANCE.md

**Comment by icepaq** [comment]
@zurgl I changed the MD file. Thanks for letting me know.

**Comment by zurgl** [comment]
All good to me, Thanks we really appreciate your contribution.
@pyr0gan could you give him an invite to the builderDao discord?  As far as I know, I can't, thanks.

**Comment by pyr0gan** [comment]
> All good to me, Thanks we really appreciate your contribution. @pyr0gan could you give him an invite to the builderDao discord? As far as I know, I can't, thanks.

Sure 😄 

@icepaq BuilderDAO Discord -> https://discord.gg/r4vNRUTXY9

**Pull request merged**
